
services:
  nginx:
    container_name: api-nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile-nginx
    depends_on:
      - api
    ports:
      - 8000:80
  api:
    container_name: api
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      - DATABASE_URL=postgresql://root:root@db:5432/fynkus?serverVersion=16&charset=utf8
      - PGPASSWORD=root
      - APP_ENV=prod
      - APP_DEBUG=0
    depends_on:
      - db
    command: >
      /bin/bash -c "
        ./sync-db.sh;
      "

  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_DB: fynkus
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root

  app:
    container_name: app
    build:
      context: .
      dockerfile: docker/Dockerfile-app
    depends_on:
      - api
    ports:
      - 3000:3000
