
services:

  api-nginx:
    container_name: api-nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile-api-nginx
    ports:
      - 8000:8000
    depends_on:
      - api
    networks:
      - fynkus
  api:
    container_name: api
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      - DATABASE_URL=postgresql://root:root@db:5432/fynkus?serverVersion=16&charset=utf8
      - PGPASSWORD=root
      - APP_ENV=prod
      - APP_DEBUG=0
      - DEFAULT_URI=http://localhost:8000
    networks:
      - fynkus
  app:
    container_name: app
    build:
      context: .
      dockerfile: docker/Dockerfile-app
    ports:
      - 3000:3000
    depends_on:
      - api
    networks:
      - fynkus

networks:
  fynkus:
    driver: bridge