FROM node:22-alpine as build-stage

WORKDIR /build

COPY app/package*.json ./
RUN npm install
COPY /app /build
RUN npm run build-only

FROM nginx:1.29-alpine as production-stage

COPY /docker/nginx/app.conf /etc/nginx/conf.d/default.conf
COPY --from=build-stage /build/dist /usr/share/nginx/html

EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]